name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 1.2.*
          
      - name: Publis .NET Project
        run: dotnet publish SchoolAPI.csproj -c Release -o release --nologo
